#!/usr/bin/env python3
import sys
file = open(sys.argv[1])

lwidth = 0
rwidth = 0

for line in file:
    parts = line.split('#',1)
    if len(parts) == 2:
        if len(parts[0]) > lwidth:
            lwidth = len(parts[0])
        if len(parts[1]) > rwidth:
            rwidth = len(parts[1].rstrip())

file.close()
file = open(sys.argv[1])

for line in file:
    parts = line.split('#', 1)
    if len(parts) == 2:
        if len(parts[0].rstrip()) != 0:
            print(parts[0].ljust(lwidth), end='')
        print('#', end='')
        print(parts[1].rstrip())
    else:
        print(line.rstrip())

        

